export enum Content {
  landing_page_get_started = "Get Started",
  landing_page_header = "The only video chat you will ever need",
  landing_page_description = "Chat with your friends and get a special experience",
  app_name = "Telemoji",
  copyright = "Copyright © ",
  login_page_username = "Email address",
  login_page_password = "Password",
  login_page_sign_in = "Sign in",
  login_page_remember_me = "Remember me",
  login_page_sign_in_button = "Sign in",
  login_page_sign_up = "Don't have an account? Sign Up",
  login_page_forgot_password = "Forgot password?",
  default_about = "Hi there, im using Telemoji! 😎",
  default_image = "https://i.pinimg.com/236x/f3/61/e3/f361e30b86fee7661463bf331de5b1b1.jpg",
  register_page_copyright = "Copyright ©",
  register_page_sign_up = "Sign up",
  register_page_first_name = "First Name",
  register_page_last_name = "Last Name",
  register_page_email_address = "Email Address",
  register_page_username = "Username",
  register_page_password = "Password",
  register_page_confirm_password = "Confirm Password",
  register_page_sign_in = "Already have an account? Sign in",
}
