export enum Content {
  app_name = "Telemoji",
  copyright = "Copyright © ",
  login_page_username = "Email address",
  login_page_password = "Password",
  login_page_sign_in = "Sign in",
  login_page_remember_me = "Remember me",
  login_page_sign_in_button = "Sign in",
  login_page_sign_up = "Don't have an account? Sign Up",
  login_page_forgot_password = "Forgot password?",
  default_about = "Hi there, im using Telemoji! 😎",
  default_image = "https://i.pinimg.com/236x/f3/61/e3/f361e30b86fee7661463bf331de5b1b1.jpg",
  forgot_password_page_login = "Back To Login Page",
  forgot_password_page_sign_up = "Don't have an account? Sign Up",
  forgot_password_page_send_email_button = "Reset Password",

  // register_page_register = "Sign up",
  // register_page_username = "Username",
  // register_page_password = "Password",
}
